realworld:
  back:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/realworld?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: 
      password: 

    exclude:
      path:
        pathList:
          - /users/login
          - /users/register
          - /articles/list
          - /articles/comments
          - /profiles/{id}
          - /articles/{id}
